<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE spamo[
<!ELEMENT spamo (model, files, primary_motif, run_time)>
<!ATTLIST spamo version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, seed, margin, bin_size,
  bin_pvalue_calc_range, bin_pvalue_cutoff, seq_max_shared_fract,
  seq_min_hit_score, redundant_overlap, redundant_joint,
  motif_pseudocount, motif_trim, bin_max, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT seed (#PCDATA)>
<!ELEMENT margin (#PCDATA)>
<!ELEMENT bin_size (#PCDATA)>
<!ELEMENT bin_pvalue_calc_range (#PCDATA)>
<!ELEMENT bin_pvalue_cutoff (#PCDATA)>
<!ELEMENT seq_max_shared_fract (#PCDATA)>
<!ELEMENT seq_min_hit_score (#PCDATA)>
<!ELEMENT redundant_overlap (#PCDATA)>
<!ELEMENT redundant_joint (#PCDATA)>
<!ELEMENT motif_pseudocount (#PCDATA)>
<!ELEMENT motif_trim (#PCDATA)>
<!ELEMENT bin_max (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT files (sequence_db, motif_db*)>
<!ELEMENT sequence_db EMPTY>
<!ATTLIST sequence_db name CDATA #REQUIRED loaded CDATA #REQUIRED
  excluded_too_short CDATA #REQUIRED excluded_no_match CDATA #REQUIRED
  excluded_similar CDATA #REQUIRED last_modified CDATA #REQUIRED
  source CDATA #REQUIRED>
<!ELEMENT motif_db EMPTY>
<!ATTLIST motif_db id ID #REQUIRED name CDATA #REQUIRED
  loaded CDATA #REQUIRED excluded CDATA #REQUIRED
  last_modified CDATA #REQUIRED source CDATA #REQUIRED
  cisml CDATA #IMPLIED>
<!ELEMENT primary_motif (motif, secondary_motif*)>
<!ELEMENT secondary_motif (spacing*, motif, histogram, redundant?)>
<!ATTLIST secondary_motif evalue CDATA #REQUIRED>
<!ELEMENT spacing EMPTY>
<!ATTLIST spacing strand (same|opposite) #REQUIRED
  side (left|right) #REQUIRED bin CDATA #REQUIRED num CDATA #REQUIRED
  pvalue CDATA #REQUIRED>
<!ELEMENT histogram (same_strand, opposite_strand)>
<!ATTLIST histogram total CDATA #REQUIRED max CDATA #REQUIRED>
<!ELEMENT same_strand (left_side, right_side)>
<!ELEMENT opposite_strand (left_side, right_side)>
<!ELEMENT left_side (bin*)>
<!ELEMENT right_side (bin*)>
<!ELEMENT bin EMPTY>
<!-- i: index, n: number in bin, p: pvalue (only supplied when bin
  is tested) -->
<!ATTLIST bin i CDATA #REQUIRED n CDATA #REQUIRED p CDATA #IMPLIED>
<!ELEMENT redundant (secondary_motif*)>
<!-- motif contains the probability of each of the nucleotide bases at each
  position; i starts at 1; A, C, G and T are probabilities that sum to 1 -->
<!ELEMENT motif (pos*)>
<!ATTLIST motif db IDREF #REQUIRED name CDATA #REQUIRED alt CDATA #IMPLIED 
  length CDATA #REQUIRED nsites CDATA #IMPLIED evalue CDATA #IMPLIED
  ltrim CDATA #IMPLIED rtrim CDATA #IMPLIED url CDATA #IMPLIED>
<!ELEMENT pos EMPTY>
<!ATTLIST pos i CDATA #REQUIRED A CDATA #REQUIRED C CDATA #REQUIRED
  G CDATA #REQUIRED T CDATA #REQUIRED>
<!-- run time is measured in real time and cpu time -->
<!ELEMENT run_time EMPTY>
<!ATTLIST run_time cpu CDATA #REQUIRED real CDATA #REQUIRED>
]>
<spamo version="4.10.0" release="Tue May 06 16:46:04 2014 +1000">
  <model>
    <command_line>spamo  -verbosity 1 -oc memechip_example_output_files/spamo_out_6 -bgfile memechip_example_output_files/background -primary MA0425.1 memechip_example_output_files/sample-dna-Klf1.fa JASPAR_CORE_2009.meme memechip_example_output_files/dreme_out/dreme.xml JASPAR_CORE_2009.meme</command_line>
    <seed>1</seed>
    <margin>150</margin>
    <bin_size>1</bin_size>
    <bin_pvalue_calc_range>150</bin_pvalue_calc_range>
    <bin_pvalue_cutoff>0.05</bin_pvalue_cutoff>
    <motif_evalue_cutoff>10</motif_evalue_cutoff>
    <seq_max_shared_fract>0.5</seq_max_shared_fract>
    <seq_min_hit_score>7</seq_min_hit_score>
    <redundant_overlap>2</redundant_overlap>
    <redundant_joint>0.5</redundant_joint>
    <motif_pseudocount>0.1</motif_pseudocount>
    <motif_trim>0.25</motif_trim>
    <bin_max>7</bin_max>
    <host>d-108-179-169-207.dhcp4.washington.edu</host>
    <when>Mon May 12 15:35:19 2014</when>
  </model>
  <files>
    <sequence_db name="sample-dna-Klf1" loaded="904" excluded_too_short="0"
        excluded_no_match="613" excluded_similar="26" last_modified="Fri May  9 16:51:44 2014"
        source="memechip_example_output_files/sample-dna-Klf1.fa"/>
    <motif_db id="primary_file" name="JASPAR CORE 2009" loaded="475" excluded="474" last_modified="Tue Dec  4 23:04:00 2012"
        source="JASPAR_CORE_2009.meme"/>
    <motif_db id="db1" name="dreme.xml" loaded="3" excluded="0" last_modified="Mon May 12 15:34:15 2014"
        source="memechip_example_output_files/dreme_out/dreme.xml"/>
    <motif_db id="db2" name="JASPAR CORE 2009" loaded="476" excluded="1" last_modified="Tue Dec  4 23:04:00 2012"
        source="JASPAR_CORE_2009.meme"/>
  </files>
  <primary_motif>
    <motif db="primary_file" name="MA0425.1" alt="YGR067C" length="14" nsites="100" evalue="0" ltrim="1" rtrim="7" url="http://jaspar.genereg.net/cgi-bin/jaspar_db.pl?ID=MA0425.1&amp;rm=present&amp;collection=CORE">
      <pos i="1" A="0.356336" C="0.23763" G="0.267304" T="0.138731"/>
      <pos i="2" A="0.000255744" C="0.999245" G="0.000243756" T="0.000255744"/>
      <pos i="3" A="0.000255744" C="0.989255" G="0.000243756" T="0.0102458"/>
      <pos i="4" A="0.000255744" C="0.999245" G="0.000243756" T="0.000255744"/>
      <pos i="5" A="0.0102458" C="0.989255" G="0.000243756" T="0.000255744"/>
      <pos i="6" A="0.409846" C="0.000243756" G="0.309934" T="0.279976"/>
      <pos i="7" A="0.000255744" C="0.979265" G="0.0102338" T="0.0102458"/>
      <pos i="8" A="0.267316" C="0.257413" G="0.168393" T="0.30688"/>
      <pos i="9" A="0.230026" C="0.259984" G="0.200044" T="0.309946"/>
      <pos i="10" A="0.240016" C="0.259984" G="0.200044" T="0.299956"/>
      <pos i="11" A="0.250006" C="0.240004" G="0.249994" T="0.259996"/>
      <pos i="12" A="0.250006" C="0.220024" G="0.259984" T="0.269986"/>
      <pos i="13" A="0.220036" C="0.259984" G="0.259984" T="0.259996"/>
      <pos i="14" A="0.257425" C="0.23763" G="0.257413" T="0.247533"/>
    </motif>
    <secondary_motif evalue="0.0037">
            <spacing strand="opposite" side="left" bin="26" num="7" pvalue="7.8e-06"/>
      <motif db="db2" name="MA0309.1" alt="GZF3" length="8" nsites="100" evalue="0" ltrim="0" rtrim="1" url="http://jaspar.genereg.net/cgi-bin/jaspar_db.pl?ID=MA0309.1&amp;rm=present&amp;collection=CORE">
        <pos i="1" A="0.180076" C="0.389854" G="0.0202238" T="0.409846"/>
        <pos i="2" A="0.000255744" C="0.000243756" G="0.999245" T="0.000255744"/>
        <pos i="3" A="0.999257" C="0.000243756" G="0.000243756" T="0.000255744"/>
        <pos i="4" A="0.000255744" C="0.000243756" G="0.000243756" T="0.999257"/>
        <pos i="5" A="0.999257" C="0.000243756" G="0.000243756" T="0.000255744"/>
        <pos i="6" A="0.729526" C="0.0901538" G="0.000243756" T="0.180076"/>
        <pos i="7" A="0.0398202" C="0.376106" G="0.583818" T="0.000255744"/>
        <pos i="8" A="0.389866" C="0.180064" G="0.269974" T="0.160096"/>
      </motif>
      <histogram total="154" max="7">
        <same_strand>
          <left_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="1" p="1"/>
            <bin i="4" n="1" p="1"/>
            <bin i="5" n="1" p="1"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="1" p="1"/>
            <bin i="16" n="1" p="1"/>
            <bin i="17" n="0"/>
            <bin i="18" n="2" p="1"/>
            <bin i="19" n="0"/>
            <bin i="20" n="1" p="1"/>
            <bin i="21" n="1" p="1"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="2" p="1"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="1" p="1"/>
            <bin i="32" n="0"/>
            <bin i="33" n="1" p="1"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="0"/>
            <bin i="46" n="1" p="1"/>
            <bin i="47" n="0"/>
            <bin i="48" n="1" p="1"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="1" p="1"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="1" p="1"/>
            <bin i="65" n="0"/>
            <bin i="66" n="1" p="1"/>
            <bin i="67" n="1" p="1"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="1" p="1"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="1" p="1"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="1" p="1"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="2" p="1"/>
            <bin i="105" n="0"/>
            <bin i="106" n="1" p="1"/>
            <bin i="107" n="1" p="1"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="1" p="1"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
            <bin i="132" n="0"/>
            <bin i="133" n="0"/>
            <bin i="134" n="0"/>
            <bin i="135" n="0"/>
            <bin i="136" n="0"/>
            <bin i="137" n="0"/>
            <bin i="138" n="0"/>
            <bin i="139" n="0"/>
            <bin i="140" n="1" p="1"/>
            <bin i="141" n="0"/>
            <bin i="142" n="0"/>
            <bin i="143" n="0"/>
            <bin i="144" n="0"/>
          </left_side>
          <right_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="1" p="1"/>
            <bin i="4" n="0"/>
            <bin i="5" n="0"/>
            <bin i="6" n="0"/>
            <bin i="7" n="0"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="1" p="1"/>
            <bin i="14" n="0"/>
            <bin i="15" n="3" p="0.77"/>
            <bin i="16" n="1" p="1"/>
            <bin i="17" n="2" p="1"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="2" p="1"/>
            <bin i="25" n="1" p="1"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="1" p="1"/>
            <bin i="33" n="1" p="1"/>
            <bin i="34" n="1" p="1"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="1" p="1"/>
            <bin i="38" n="0"/>
            <bin i="39" n="0"/>
            <bin i="40" n="0"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="1" p="1"/>
            <bin i="45" n="1" p="1"/>
            <bin i="46" n="1" p="1"/>
            <bin i="47" n="0"/>
            <bin i="48" n="1" p="1"/>
            <bin i="49" n="0"/>
            <bin i="50" n="0"/>
            <bin i="51" n="0"/>
            <bin i="52" n="2" p="1"/>
            <bin i="53" n="0"/>
            <bin i="54" n="1" p="1"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="1" p="1"/>
            <bin i="58" n="0"/>
            <bin i="59" n="1" p="1"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="1" p="1"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="1" p="1"/>
            <bin i="68" n="1" p="1"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="1" p="1"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="1" p="1"/>
            <bin i="89" n="1" p="1"/>
            <bin i="90" n="0"/>
            <bin i="91" n="0"/>
            <bin i="92" n="1" p="1"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="1" p="1"/>
            <bin i="97" n="1" p="1"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="0"/>
            <bin i="101" n="0"/>
            <bin i="102" n="1" p="1"/>
            <bin i="103" n="1" p="1"/>
            <bin i="104" n="0"/>
            <bin i="105" n="2" p="1"/>
            <bin i="106" n="1" p="1"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="1" p="1"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="1" p="1"/>
            <bin i="130" n="0"/>
            <bin i="131" n="0"/>
            <bin i="132" n="0"/>
            <bin i="133" n="0"/>
            <bin i="134" n="0"/>
            <bin i="135" n="0"/>
            <bin i="136" n="0"/>
            <bin i="137" n="1" p="1"/>
            <bin i="138" n="0"/>
            <bin i="139" n="0"/>
            <bin i="140" n="0"/>
            <bin i="141" n="0"/>
            <bin i="142" n="0"/>
            <bin i="143" n="0"/>
            <bin i="144" n="0"/>
          </right_side>
        </same_strand>
        <opposite_strand>
          <left_side>
            <bin i="1" n="0"/>
            <bin i="2" n="1" p="1"/>
            <bin i="3" n="0"/>
            <bin i="4" n="2" p="1"/>
            <bin i="5" n="2" p="1"/>
            <bin i="6" n="1" p="1"/>
            <bin i="7" n="0"/>
            <bin i="8" n="1" p="1"/>
            <bin i="9" n="0"/>
            <bin i="10" n="0"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="0"/>
            <bin i="15" n="0"/>
            <bin i="16" n="1" p="1"/>
            <bin i="17" n="1" p="1"/>
            <bin i="18" n="1" p="1"/>
            <bin i="19" n="1" p="1"/>
            <bin i="20" n="2" p="1"/>
            <bin i="21" n="0"/>
            <bin i="22" n="2" p="1"/>
            <bin i="23" n="0"/>
            <bin i="24" n="0"/>
            <bin i="25" n="2" p="1"/>
            <bin i="26" n="7" p="7.8e-06"/>
            <bin i="27" n="0"/>
            <bin i="28" n="0"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="1" p="1"/>
            <bin i="32" n="2" p="1"/>
            <bin i="33" n="1" p="1"/>
            <bin i="34" n="0"/>
            <bin i="35" n="0"/>
            <bin i="36" n="0"/>
            <bin i="37" n="0"/>
            <bin i="38" n="1" p="1"/>
            <bin i="39" n="0"/>
            <bin i="40" n="1" p="1"/>
            <bin i="41" n="0"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="1" p="1"/>
            <bin i="45" n="0"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="0"/>
            <bin i="49" n="0"/>
            <bin i="50" n="1" p="1"/>
            <bin i="51" n="0"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="0"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="0"/>
            <bin i="64" n="1" p="1"/>
            <bin i="65" n="0"/>
            <bin i="66" n="0"/>
            <bin i="67" n="1" p="1"/>
            <bin i="68" n="0"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="1" p="1"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="1" p="1"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="0"/>
            <bin i="82" n="1" p="1"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="0"/>
            <bin i="90" n="0"/>
            <bin i="91" n="1" p="1"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="2" p="1"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="0"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="1" p="1"/>
            <bin i="112" n="0"/>
            <bin i="113" n="0"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="0"/>
            <bin i="118" n="1" p="1"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="1" p="1"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="0"/>
            <bin i="131" n="2" p="1"/>
            <bin i="132" n="1" p="1"/>
            <bin i="133" n="0"/>
            <bin i="134" n="0"/>
            <bin i="135" n="0"/>
            <bin i="136" n="0"/>
            <bin i="137" n="0"/>
            <bin i="138" n="0"/>
            <bin i="139" n="0"/>
            <bin i="140" n="1" p="1"/>
            <bin i="141" n="0"/>
            <bin i="142" n="0"/>
            <bin i="143" n="0"/>
            <bin i="144" n="0"/>
          </left_side>
          <right_side>
            <bin i="1" n="0"/>
            <bin i="2" n="0"/>
            <bin i="3" n="1" p="1"/>
            <bin i="4" n="1" p="1"/>
            <bin i="5" n="1" p="1"/>
            <bin i="6" n="2" p="1"/>
            <bin i="7" n="2" p="1"/>
            <bin i="8" n="0"/>
            <bin i="9" n="0"/>
            <bin i="10" n="1" p="1"/>
            <bin i="11" n="0"/>
            <bin i="12" n="0"/>
            <bin i="13" n="0"/>
            <bin i="14" n="2" p="1"/>
            <bin i="15" n="0"/>
            <bin i="16" n="0"/>
            <bin i="17" n="0"/>
            <bin i="18" n="0"/>
            <bin i="19" n="0"/>
            <bin i="20" n="0"/>
            <bin i="21" n="0"/>
            <bin i="22" n="0"/>
            <bin i="23" n="0"/>
            <bin i="24" n="1" p="1"/>
            <bin i="25" n="0"/>
            <bin i="26" n="0"/>
            <bin i="27" n="0"/>
            <bin i="28" n="1" p="1"/>
            <bin i="29" n="0"/>
            <bin i="30" n="0"/>
            <bin i="31" n="0"/>
            <bin i="32" n="0"/>
            <bin i="33" n="1" p="1"/>
            <bin i="34" n="0"/>
            <bin i="35" n="2" p="1"/>
            <bin i="36" n="2" p="1"/>
            <bin i="37" n="1" p="1"/>
            <bin i="38" n="0"/>
            <bin i="39" n="1" p="1"/>
            <bin i="40" n="0"/>
            <bin i="41" n="1" p="1"/>
            <bin i="42" n="0"/>
            <bin i="43" n="0"/>
            <bin i="44" n="0"/>
            <bin i="45" n="1" p="1"/>
            <bin i="46" n="0"/>
            <bin i="47" n="0"/>
            <bin i="48" n="1" p="1"/>
            <bin i="49" n="1" p="1"/>
            <bin i="50" n="0"/>
            <bin i="51" n="1" p="1"/>
            <bin i="52" n="0"/>
            <bin i="53" n="0"/>
            <bin i="54" n="0"/>
            <bin i="55" n="0"/>
            <bin i="56" n="0"/>
            <bin i="57" n="0"/>
            <bin i="58" n="0"/>
            <bin i="59" n="0"/>
            <bin i="60" n="1" p="1"/>
            <bin i="61" n="0"/>
            <bin i="62" n="0"/>
            <bin i="63" n="1" p="1"/>
            <bin i="64" n="0"/>
            <bin i="65" n="1" p="1"/>
            <bin i="66" n="1" p="1"/>
            <bin i="67" n="0"/>
            <bin i="68" n="1" p="1"/>
            <bin i="69" n="0"/>
            <bin i="70" n="0"/>
            <bin i="71" n="0"/>
            <bin i="72" n="0"/>
            <bin i="73" n="0"/>
            <bin i="74" n="0"/>
            <bin i="75" n="0"/>
            <bin i="76" n="0"/>
            <bin i="77" n="0"/>
            <bin i="78" n="0"/>
            <bin i="79" n="0"/>
            <bin i="80" n="0"/>
            <bin i="81" n="1" p="1"/>
            <bin i="82" n="0"/>
            <bin i="83" n="0"/>
            <bin i="84" n="0"/>
            <bin i="85" n="0"/>
            <bin i="86" n="0"/>
            <bin i="87" n="0"/>
            <bin i="88" n="0"/>
            <bin i="89" n="1" p="1"/>
            <bin i="90" n="0"/>
            <bin i="91" n="1" p="1"/>
            <bin i="92" n="0"/>
            <bin i="93" n="0"/>
            <bin i="94" n="0"/>
            <bin i="95" n="0"/>
            <bin i="96" n="0"/>
            <bin i="97" n="0"/>
            <bin i="98" n="0"/>
            <bin i="99" n="0"/>
            <bin i="100" n="1" p="1"/>
            <bin i="101" n="0"/>
            <bin i="102" n="0"/>
            <bin i="103" n="0"/>
            <bin i="104" n="0"/>
            <bin i="105" n="0"/>
            <bin i="106" n="0"/>
            <bin i="107" n="0"/>
            <bin i="108" n="1" p="1"/>
            <bin i="109" n="0"/>
            <bin i="110" n="0"/>
            <bin i="111" n="0"/>
            <bin i="112" n="0"/>
            <bin i="113" n="2" p="1"/>
            <bin i="114" n="0"/>
            <bin i="115" n="0"/>
            <bin i="116" n="0"/>
            <bin i="117" n="1" p="1"/>
            <bin i="118" n="0"/>
            <bin i="119" n="0"/>
            <bin i="120" n="0"/>
            <bin i="121" n="0"/>
            <bin i="122" n="0"/>
            <bin i="123" n="0"/>
            <bin i="124" n="0"/>
            <bin i="125" n="0"/>
            <bin i="126" n="0"/>
            <bin i="127" n="0"/>
            <bin i="128" n="0"/>
            <bin i="129" n="0"/>
            <bin i="130" n="1" p="1"/>
            <bin i="131" n="0"/>
            <bin i="132" n="0"/>
            <bin i="133" n="0"/>
            <bin i="134" n="0"/>
            <bin i="135" n="0"/>
            <bin i="136" n="0"/>
            <bin i="137" n="0"/>
            <bin i="138" n="0"/>
            <bin i="139" n="0"/>
            <bin i="140" n="0"/>
            <bin i="141" n="0"/>
            <bin i="142" n="0"/>
            <bin i="143" n="0"/>
            <bin i="144" n="0"/>
          </right_side>
        </opposite_strand>
      </histogram>
      <redundant>
        <secondary_motif evalue="0.056">
                    <spacing strand="opposite" side="left" bin="26" num="6" pvalue="0.00012"/>
          <motif db="db2" name="MA0300.1" alt="GAT1" length="8" nsites="100" evalue="0" ltrim="1" rtrim="0" url="http://jaspar.genereg.net/cgi-bin/jaspar_db.pl?ID=MA0300.1&amp;rm=present&amp;collection=CORE">
            <pos i="1" A="0.12884" C="0.435453" G="0.188175" T="0.247533"/>
            <pos i="2" A="0.170086" C="0.419824" G="0.0501938" T="0.359896"/>
            <pos i="3" A="0.000255744" C="0.000243756" G="0.999245" T="0.000255744"/>
            <pos i="4" A="0.999257" C="0.000243756" G="0.000243756" T="0.000255744"/>
            <pos i="5" A="0.000255744" C="0.000243756" G="0.000243756" T="0.999257"/>
            <pos i="6" A="0.999257" C="0.000243756" G="0.000243756" T="0.000255744"/>
            <pos i="7" A="0.999257" C="0.000243756" G="0.000243756" T="0.000255744"/>
            <pos i="8" A="0.0305285" C="0.0910619" G="0.847881" T="0.0305285"/>
          </motif>
          <histogram total="139" max="6">
            <same_strand>
              <left_side>
                <bin i="1" n="0"/>
                <bin i="2" n="0"/>
                <bin i="3" n="0"/>
                <bin i="4" n="0"/>
                <bin i="5" n="1" p="1"/>
                <bin i="6" n="0"/>
                <bin i="7" n="0"/>
                <bin i="8" n="0"/>
                <bin i="9" n="0"/>
                <bin i="10" n="0"/>
                <bin i="11" n="0"/>
                <bin i="12" n="0"/>
                <bin i="13" n="0"/>
                <bin i="14" n="0"/>
                <bin i="15" n="1" p="1"/>
                <bin i="16" n="1" p="1"/>
                <bin i="17" n="0"/>
                <bin i="18" n="2" p="1"/>
                <bin i="19" n="0"/>
                <bin i="20" n="1" p="1"/>
                <bin i="21" n="1" p="1"/>
                <bin i="22" n="0"/>
                <bin i="23" n="0"/>
                <bin i="24" n="0"/>
                <bin i="25" n="2" p="1"/>
                <bin i="26" n="0"/>
                <bin i="27" n="0"/>
                <bin i="28" n="0"/>
                <bin i="29" n="0"/>
                <bin i="30" n="0"/>
                <bin i="31" n="0"/>
                <bin i="32" n="0"/>
                <bin i="33" n="1" p="1"/>
                <bin i="34" n="0"/>
                <bin i="35" n="0"/>
                <bin i="36" n="0"/>
                <bin i="37" n="0"/>
                <bin i="38" n="0"/>
                <bin i="39" n="0"/>
                <bin i="40" n="0"/>
                <bin i="41" n="0"/>
                <bin i="42" n="0"/>
                <bin i="43" n="0"/>
                <bin i="44" n="0"/>
                <bin i="45" n="0"/>
                <bin i="46" n="1" p="1"/>
                <bin i="47" n="0"/>
                <bin i="48" n="1" p="1"/>
                <bin i="49" n="0"/>
                <bin i="50" n="0"/>
                <bin i="51" n="0"/>
                <bin i="52" n="0"/>
                <bin i="53" n="0"/>
                <bin i="54" n="0"/>
                <bin i="55" n="0"/>
                <bin i="56" n="0"/>
                <bin i="57" n="0"/>
                <bin i="58" n="0"/>
                <bin i="59" n="0"/>
                <bin i="60" n="1" p="1"/>